### ISSUE TITLE
discr column

### ISSUE THREAD

**Issue by n0nick2010** [mysql-workbench-schema-exporter/mysql-workbench-schema-exporter#102]
hello,

i use the base table option (very nice feature), but now i have the following doctrine error in my project:

Duplicate definition of column 'discr' on entity....

The Problem is in the Base-Classes:
"   /**
     \* @ORM\Column(type="string", length=100, nullable=true)
     */
    protected $discr;"

How can I create the entities without this field? Is there an option?

Thanks

**Comment by malutanpetronel** [comment]
I did tried to switch to annotations so I did exported with extended class using:

{
	"export": "doctrine2-annotation",
	"zip": false,
	"dir": "mwb-data/sf2-result",
	"params": {
		"indentation": 4,
		"useTabs": true,
		"filename": "%entity%.%extension%",
		"skipPluralNameChecking": false,
		"backupExistingFile": false,
		"useLoggedStorage": false,
		"enhanceManyToManyDetection": true,
		"useAnnotationPrefix": "ORM\\",
		"bundleNamespace": "",
		"entityNamespace": "Blogger\\BlogBundle\\Entity",
		"repositoryNamespace": "Blogger\\BlogBundle\\Entity\\Repository",
		"useAutomaticRepository": true,
		"skipGetterAndSetter": false,
		"generateEntitySerialization": true,
		"quoteIdentifier": false,
		"generateExtendableEntity": true
	}
}

the following 2 classes

<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-05-11 20:32:00.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Blogger\BlogBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Blogger\BlogBundle\Entity\BaseBlog;

/**
 * Blogger\BlogBundle\Entity\Blog
 *
 * @ORM\Entity(repositoryClass="Blogger\BlogBundle\Entity\Repository\BlogRepository")
 */
class Blog extends BaseBlog
{
}

################

<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2015-05-11 20:32:00.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Blogger\BlogBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Blogger\BlogBundle\Entity\Blog
 *
 * @ORM\Entity(repositoryClass="Blogger\BlogBundle\Entity\Repository\BlogRepository")
 * @ORM\Table(name="blog", indexes={@ORM\Index(name="author_index", columns={"author"})})
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn(name="discr", type="string")
 * @ORM\DiscriminatorMap({"base":"BaseBlog", "extended":"Blog"})
 * @ORM\HasLifecycleCallbacks
 */
class BaseBlog
{
	/**
	 * @ORM\Id
	 * @ORM\Column(type="integer")
	 * @ORM\GeneratedValue(strategy="AUTO")
	 */
	protected $id;

	/**
	 * @ORM\Column(type="string", length=45, nullable=true)
	 */
	protected $title;

	/**
	 * This will keep the slug for the blog. The size of field was estimated to
	 * 45/3letters word + - which will replace the spaces
	 *
	 * @ORM\Column(type="string", length=60, nullable=true)
	 */
	protected $slug;

	/**
	 * @ORM\Column(type="string", length=100, nullable=true)
	 */
	protected $author;

	/**
	 * @ORM\Column(type="text", nullable=true)
	 */
	protected $blog;

	/**
	 * @ORM\Column(type="string", length=20, nullable=true)
	 */
	protected $image;

	/**
	 * @ORM\Column(type="text", nullable=true)
	 */
	protected $tags;

	/**
	 * @ORM\Column(type="datetime", nullable=true)
	 */
	protected $created;

	/**
	 * @ORM\Column(type="datetime", nullable=true)
	 */
	protected $updated;

	/**
	 * @ORM\OneToMany(targetEntity="Comment", mappedBy="blog", cascade={"remove"})
	 * @ORM\JoinColumn(name="id", referencedColumnName="blog_id", onDelete="CASCADE")
	 */
	protected $comments;

	/**
	 * @ORM\ManyToMany(targetEntity="Cat", inversedBy="blogs")
	 * @ORM\JoinTable(name="blog_has_cat",
	 *     joinColumns={@ORM\JoinColumn(name="blog_id", referencedColumnName="id", onDelete="CASCADE")},
	 *     inverseJoinColumns={@ORM\JoinColumn(name="cat_id", referencedColumnName="id", onDelete="CASCADE")}
	 * )
	 */
	protected $cats;

	public function __construct()
	{
		$this->comments = new ArrayCollection();
		$this->cats = new ArrayCollection();
	}

	/**
	 * Set the value of id.
	 *
	 * @param integer $id
	 * @return \Blogger\BlogBundle\Entity\Blog
	 */
	public function setId($id)
	{
		$this->id = $id;

		return $this;
	}

	/**
	 * Get the value of id.
	 *
	 * @return integer
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Set the value of title.
	 *
	 * @param string $title
	 * @return \Blogger\BlogBundle\Entity\Blog
	 */
	public function setTitle($title)
	{
		$this->title = $title;

		return $this;
	}

	/**
	 * Get the value of title.
	 *
	 * @return string
	 */
	public function getTitle()
	{
		return $this->title;
	}

	/**
	 * Set the value of slug.
	 *
	 * @param string $slug
	 * @return \Blogger\BlogBundle\Entity\Blog
	 */
	public function setSlug($slug)
	{
		$this->slug = $slug;

		return $this;
	}

	/**
	 * Get the value of slug.
	 *
	 * @return string
	 */
	public function getSlug()
	{
		return $this->slug;
	}

	/**
	 * Set the value of author.
	 *
	 * @param string $author
	 * @return \Blogger\BlogBundle\Entity\Blog
	 */
	public function setAuthor($author)
	{
		$this->author = $author;

		return $this;
	}

	/**
	 * Get the value of author.
	 *
	 * @return string
	 */
	public function getAuthor()
	{
		return $this->author;
	}

	/**
	 * Set the value of blog.
	 *
	 * @param string $blog
	 * @return \Blogger\BlogBundle\Entity\Blog
	 */
	public function setBlog($blog)
	{
		$this->blog = $blog;

		return $this;
	}

	/**
	 * Get the value of blog.
	 *
	 * @return string
	 */
	public function getBlog()
	{
		return $this->blog;
	}

	/**
	 * Set the value of image.
	 *
	 * @param string $image
	 * @return \Blogger\BlogBundle\Entity\Blog
	 */
	public function setImage($image)
	{
		$this->image = $image;

		return $this;
	}

	/**
	 * Get the value of image.
	 *
	 * @return string
	 */
	public function getImage()
	{
		return $this->image;
	}

	/**
	 * Set the value of tags.
	 *
	 * @param string $tags
	 * @return \Blogger\BlogBundle\Entity\Blog
	 */
	public function setTags($tags)
	{
		$this->tags = $tags;

		return $this;
	}

	/**
	 * Get the value of tags.
	 *
	 * @return string
	 */
	public function getTags()
	{
		return $this->tags;
	}

	/**
	 * Set the value of created.
	 *
	 * @param \DateTime $created
	 * @return \Blogger\BlogBundle\Entity\Blog
	 */
	public function setCreated($created)
	{
		$this->created = $created;

		return $this;
	}

	/**
	 * Get the value of created.
	 *
	 * @return \DateTime
	 */
	public function getCreated()
	{
		return $this->created;
	}

	/**
	 * Set the value of updated.
	 *
	 * @param \DateTime $updated
	 * @return \Blogger\BlogBundle\Entity\Blog
	 */
	public function setUpdated($updated)
	{
		$this->updated = $updated;

		return $this;
	}

	/**
	 * Get the value of updated.
	 *
	 * @return \DateTime
	 */
	public function getUpdated()
	{
		return $this->updated;
	}

	/**
	 * Add Comment entity to collection (one to many).
	 *
	 * @param \Blogger\BlogBundle\Entity\Comment $comment
	 * @return \Blogger\BlogBundle\Entity\Blog
	 */
	public function addComment(Comment $comment)
	{
		$this->comments[] = $comment;

		return $this;
	}

	/**
	 * Remove Comment entity from collection (one to many).
	 *
	 * @param \Blogger\BlogBundle\Entity\Comment $comment
	 * @return \Blogger\BlogBundle\Entity\Blog
	 */
	public function removeComment(Comment $comment)
	{
		$this->comments->removeElement($comment);

		return $this;
	}

	/**
	 * Get Comment entity collection (one to many).
	 *
	 * @return \Doctrine\Common\Collections\Collection
	 */
	public function getComments()
	{
		return $this->comments;
	}

	/**
	 * Add Cat entity to collection.
	 *
	 * @param \Blogger\BlogBundle\Entity\Cat $cat
	 * @return \Blogger\BlogBundle\Entity\Blog
	 */
	public function addCat(Cat $cat)
	{
		$cat->addBlog($this);
		$this->cats[] = $cat;

		return $this;
	}

	/**
	 * Remove Cat entity from collection.
	 *
	 * @param \Blogger\BlogBundle\Entity\Cat $cat
	 * @return \Blogger\BlogBundle\Entity\Blog
	 */
	public function removeCat(Cat $cat)
	{
		$cat->removeBlog($this);
		$this->cats->removeElement($cat);

		return $this;
	}

	/**
	 * Get Cat entity collection.
	 *
	 * @return \Doctrine\Common\Collections\Collection
	 */
	public function getCats()
	{
		return $this->cats;
	}

	/**
	 * @ORM\PostLoad
	 */
	public function fnc_postLoad()
	{
	}

	/**
	 * @ORM\PrePersist
	 */
	public function fnc_prePersist()
	{
	}

	/**
	 * @ORM\PostPersist
	 */
	public function fnc_postPersist()
	{
	}

	/**
	 * @ORM\PreRemove
	 */
	public function fnc_preRemove()
	{
	}

	/**
	 * @ORM\PostRemove
	 */
	public function fnc_postRemove()
	{
	}

	/**
	 * @ORM\PreUpdate
	 */
	public function fnc_preUpdate()
	{
	}

	/**
	 * @ORM\PostUpdate
	 */
	public function fnc_postUpdate()
	{
	}

	public function __sleep()
	{
		return array('id', 'title', 'slug', 'author', 'blog', 'image', 'tags', 'created', 'updated');
	}
}


################

but this seems to drop error

An exception occurred while executing 'SELECT b0_.id AS id0, b0_.title AS title1, b0_.slug AS slug2, b0_.author AS author3, b0_.blog AS blog4, b0_.image AS image5, b0_.tags AS tags6, b0_.created AS created7, b0_.updated AS updated8, c1_.id AS id9, c1_.`user` AS user10, c1_.`comment` AS comment11, c1_.approoved AS approoved12, c1_.blog_id AS blog_id13, c1_.created AS created14, c1_.updated AS updated15, b0_.discr AS discr16, c1_.discr AS discr17, c1_.blog_id AS blog_id18 FROM Blog b2_ INNER JOIN blog b0_ ON b2_.id = b0_.id LEFT JOIN comment c1_ ON b0_.id = c1_.blog_id AND c1_.discr IN ('extended') ORDER BY b0_.created DESC':

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'symfony_blog.Blog' doesn't exist

### as it seems to search a table Blog when that is in fact blog

any hints on how to fix these ?

**Comment by malutanpetronel** [comment]
Basically it works exporting when using ORM, but when switched to annotations the error is the one above... it seems something not work as expected. Is the 

 * @ORM\Entity(repositoryClass="Blogger\BlogBundle\Entity\Repository\BlogRepository")
 * @ORM\Table(name="blog", indexes={@ORM\Index(name="author_index", columns={"author"})})
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn(name="discr", type="string")
 * @ORM\DiscriminatorMap({"base":"BaseBlog", "extended":"Blog"})
 * @ORM\HasLifecycleCallbacks
 
abovr correct ? note the table is blog ...

**Comment by malutanpetronel** [comment]
An exception occurred while executing 'SELECT b0_.id AS id0, b0_.title AS title1, b0_.slug AS slug2, b0_.author AS author3, b0_.blog AS blog4, b0_.image AS image5, b0_.tags AS tags6, b0_.created AS created7, b0_.updated AS updated8, c1_.id AS id9, c1_.`user` AS user10, c1_.`comment` AS comment11, c1_.approoved AS approoved12, c1_.blog_id AS blog_id13, c1_.created AS created14, c1_.updated AS updated15, b0_.discr1 AS discr116, c1_.discr3 AS discr317, c1_.blog_id AS blog_id18 FROM blog b0_ LEFT JOIN comment c1_ ON b0_.id = c1_.blog_id AND c1_.discr3 IN ('extended') WHERE b0_.discr1 IN ('extended') ORDER BY b0_.created DESC':

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'b0_.discr1' in 'field list'
500 Internal Server Error - DBALException
1 linked Exception:

    PDOException »
