### ISSUE TITLE
One To Many Relation Creates Both variable & object (doctrine2 annotation)

### ISSUE THREAD

**Issue by fliespl** [mysql-workbench-schema-exporter/mysql-workbench-schema-exporter#133]
Hi,
first of all I wanted to say thank you for your great work on this code - it helps a lot. :)

Today I've come up with a problem generating Entities from simple schema.

It consists of three tables: http://codeone.pl/ss/ss-2015-02-09_19-38-52-001.png

After generating Entities I got in UserRole Entity: http://codeone.pl/ss/ss-2015-02-09_19-36-20-001.png both variables (user_id, role_id) & setters for Entityies (User, Role).

This caused fixtures code not to be able to execute unless I provide both model & variables:
setUser($user) & setUserId($id)
setRole($role) & setRoleId($id)

Is there any way I can change this behaviour that it would only generate Model without variables and set them as primary composite key?

Target (valid) Entity: http://codeone.pl/ss/ss-2015-02-09_19-38-28-001.png

Thanks!

**Comment by fliespl** [comment]
After looking into the code I have traversed that this issue is connected with isIgnored function inside Column. In my case it's returned as false since it's primary key - I believe that composite keys should be excluded from "isPrimary" check - if I remove them primary key they work correctly.

**Comment by tohenk** [comment]
Try ```skipColumnWithRelation``` set to ```true``` in your configuration.

**Comment by fliespl** [comment]
Hi @tohenk,
actually in this case it won't work. skipColumnWithRelation switch is never used, bacause it's after check "isPrimary" (composite key is also primary).

**Comment by tohenk** [comment]
Closing now, if the problem still exist, open the issue in the related project.
