### ISSUE TITLE
Laravel 5 Migrations and Models 

### ISSUE THREAD

**Issue by shellprog** [mysql-workbench-schema-exporter/mysql-workbench-schema-exporter#134]
Any one started on Laravel Integration ? I would like to join to speed up the process .

**Comment by tohenk** [comment]
You can clone this repository and made modifications. I'm sure everyone will be willingly review your code.
To start, just see already existing formatter. Also, try to use as much as possible the code style used in existing code.

**Comment by shellprog** [comment]
There is already a package for it . 

https://packagist.org/packages/xethron/migrations-generator

**Comment by kohloth** [comment]
@shellprog I think the xethron package only creates laravel migrations from an actual database, not a mysql workbench .mwb file.

**Comment by vitalibr** [comment]
@shellprog 
I done the plugin to Laravel 5.0 Model and Migration, but there are still some adjustments. 
I hope your collaboration.

https://packagist.org/packages/vitalibr/laravel5-exporter
