### ISSUE TITLE
Doctrine2 annotations - Typehints

### ISSUE THREAD

**Issue by chapcz** [mysql-workbench-schema-exporter/mysql-workbench-schema-exporter#144]
Hi, I would like to ask about new feature Typehints. I really like to use this, but when I tried to export with Formatter::CFG_PROPERTY_TYPEHINT         => TRUE/FALSE .... I had same result. Can you help me please? I only changed Setup file in example folder. 
And my second question ... is there possible to generate from property named for example 
column_name  => columnName ? 
Thanks, Chap

**Comment by rvock** [comment]
Hello chapcz,

this config option only applies to values for normal fields and not for relations. This means, if you enable typehints, only \DateTime will be added to date-fields. Disabling typehints will not disable the typehints for the relation getter and setter functions. I would vote to remove this option completely and always output typehints.

Currently there is no option to define the naming strategy for fields. So if you want columnName, you need to name the field columnName in MySQL-Workbench.

**Comment by tohenk** [comment]
Closing now, open the issue in the related project.
