### ISSUE TITLE
Multiple inheritance

### ISSUE THREAD

**Issue by malutanpetronel** [mysql-workbench-schema-exporter/mysql-workbench-schema-exporter#147]
Hi

I've managed to export a baseBlog and Blog entity.
What I am wondering is how a multiple inheritance MWB would look like ?
Can you include on in the example or pass me a link here to download a simple one here ?

With kind regards

**Comment by allansun** [comment]
I am not aware of such inheritance, could you describe it with a bit more details please?

**Comment by malutanpetronel** [comment]
Hi Allan

You know you can export with annotation and generateExtendableEntity which is fine but what if you would like to have the 2 models in diagram:

ITEM
id
name

and something which extend MODULE

PRODUCT
id
price

this second model need to extend the ITEM and need a sort of annotation in the MWB comments I guess, to be able to have a class generated for PRODUCT 

http://doctrine-orm.readthedocs.org/en/latest/reference/inheritance-mapping.html#class-table-inheritance
(see there that DiscriminatorMap contains both other classes from "MWB schema" Person and Employee
 * @DiscriminatorMap({"person" = "Person", "employee" = "Employee"})

So in order to get such a Class Table Inheritance we would need to have in MWB

ITEM           PRODUCT		 SPECIAL
id  ----------   id                      ... id
name           price			 someField
               (some comment 	(same comment)
               to say			SPECIAL extend ITEM 
               PRODUCT extend 
              ITEM)					

in this way the generator will have to generate
BaseItem
Item wich extend BaseItem
Product Which extend Item

Not sure if anyone use it and I've made myself understood ?

**Comment by allansun** [comment]
I think what you are referring to is to establish relationships between
tables. Use foreign keys. Press '2' and then click the tables you want to
link from and to. Try re-export the files again.

On 2015年8月12日 周三 at 下午1:19 Petronel MALUTAN <notifications@github.com>
wrote:

> Hi Allan
>
> You know you can export with annotation and generateExtendableEntity which
> is fine but what if you would like to have the 2 models in diagram:
>
> ITEM
> id
> name
>
> and something which extend MODULE
>
> PRODUCT
> id
> price
>
> this second model need to extend the ITEM and need a sort of annotation in
> the MWB comments I guess, to be able to have a class generated for PRODUCT
>
>
> http://doctrine-orm.readthedocs.org/en/latest/reference/inheritance-mapping.html#class-table-inheritance
> (see there that DiscriminatorMap contains both other classes from "MWB
> schema" Person and Employee
>
>    - @DiscriminatorMap({"person" = "Person", "employee" = "Employee"})
>
> So in order to get such a Class Table Inheritance we would need to have in
> MWB
>
> ITEM PRODUCT SPECIAL
> id ---------- id ... id
> name price someField
> (some comment (same comment)
> to say SPECIAL extend ITEM
> PRODUCT extend
> ITEM)
>
> in this way the generator will have to generate
> BaseItem
> Item wich extend BaseItem
> Product Which extend Item
>
> Not sure if anyone use it and I've made myself understood ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/johmue/mysql-workbench-schema-exporter/issues/147#issuecomment-130280863>
> .
>
-- 
Best regards,

Allan Sun

**Comment by allansun** [comment]
Hmm after rethink I might have misunderstood you.

You are talking about Doctrine extending model, I personally never used
Doctrine for any real projects. Maybe other guys can help?

On 2015年8月12日 周三 at 下午2:15 Allan Sun <sunajia@gmail.com> wrote:

> I think what you are referring to is to establish relationships between
> tables. Use foreign keys. Press '2' and then click the tables you want to
> link from and to. Try re-export the files again.
>
> On 2015年8月12日 周三 at 下午1:19 Petronel MALUTAN <notifications@github.com>
> wrote:
>
>> Hi Allan
>>
>> You know you can export with annotation and generateExtendableEntity
>> which is fine but what if you would like to have the 2 models in diagram:
>>
>> ITEM
>> id
>> name
>>
>> and something which extend MODULE
>>
>> PRODUCT
>> id
>> price
>>
>> this second model need to extend the ITEM and need a sort of annotation
>> in the MWB comments I guess, to be able to have a class generated for
>> PRODUCT
>>
>>
>> http://doctrine-orm.readthedocs.org/en/latest/reference/inheritance-mapping.html#class-table-inheritance
>> (see there that DiscriminatorMap contains both other classes from "MWB
>> schema" Person and Employee
>>
>>    - @DiscriminatorMap({"person" = "Person", "employee" = "Employee"})
>>
>> So in order to get such a Class Table Inheritance we would need to have
>> in MWB
>>
>> ITEM PRODUCT SPECIAL
>> id ---------- id ... id
>> name price someField
>> (some comment (same comment)
>> to say SPECIAL extend ITEM
>> PRODUCT extend
>> ITEM)
>>
>> in this way the generator will have to generate
>> BaseItem
>> Item wich extend BaseItem
>> Product Which extend Item
>>
>> Not sure if anyone use it and I've made myself understood ?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/johmue/mysql-workbench-schema-exporter/issues/147#issuecomment-130280863>
>> .
>>
> --
> Best regards,
>
> Allan Sun

-- 
Best regards,

Allan Sun

**Comment by tohenk** [comment]
Closing now, open the issue in the related project.
