### ISSUE TITLE
Mysql NCHAR Data Type

### ISSUE THREAD

**Issue by victorfcm** [mysql-workbench-schema-exporter/mysql-workbench-schema-exporter#151]
Error:
Unknown data type "com.mysql.rdbms.mysql.datatype.nchar"

Mysql Workbench version 6.3
Mysql Server version 5.5.44

Type of the field as shown on the Workbench: CHAR(10).

I really don't know what is happening here.

**Comment by victorfcm** [comment]
I search a little bit and I've found this: 

The problem is that the Workbench 6.3 is adapted to Mysql Server 5.7, and you're using 5.5, so he interpret that CHAR(10) is a national character (https://dev.mysql.com/doc/refman/5.7/en/charset-national.html) and that's the problem.

In fact, when I change CHAR(10) to VARCHAR(10), works fine.

**Comment by tohenk** [comment]
Fixed in e10b70cb435a908ec1bf05b1e2252626b14489a2.

**Comment by victorfcm** [comment]
Thank you! A little late, but thank u :+1:
