### ISSUE TITLE
list-exporter is broken

### ISSUE THREAD

**Issue by knifesk** [mysql-workbench-schema-exporter/mysql-workbench-schema-exporter#155]
Issuing list exporter option produces an error.

```
php bin/mysql-workbench-schema-export --list-exporter
MySQL Workbench Schema Exporter version 2.1.6-dev.
Copyright (c) 2010-2014 Johannes Mueller <circus2@web.de>
Copyright (c) 2012-2014 Toha <tohenk@yahoo.com>

Supported exporter:
PHP Warning:  max(): Array must contain at least one element in /media/datos/home/martin/www/mysql-workbench-schema-exporter/bin/mysql-workbench-schema-export on line 204

Warning: max(): Array must contain at least one element in /media/datos/home/martin/www/mysql-workbench-schema-exporter/bin/mysql-workbench-schema-export on line 204
```
I know its not a show-killer bug, but for a newcomer like me its kinda bumer :p

(edit:)
Btw! PHP ver is 5.4.45 (cli)

Cheers!

**Comment by knifesk** [comment]
This issue is not an issue itself.. Problem is that the documentation doesn't says that exporters are in separate projects and that need to be downloaded individually. If the documentation explicitly says this please ignore this issue completely, probably I overlooked something.. 

Thanks in advance!

**Comment by johmue** [comment]
Hi, the project is currently in a restructuring phase (split in separate packages and moved to a github organization). The documentation is therefore not up-to-date.
