### ISSUE TITLE
exporter list is empty

### ISSUE THREAD

**Issue by elgui02** [mysql-workbench-schema-exporter/mysql-workbench-schema-exporter#156]
Hi i download the last update when a run a: php bin/mysql-workbench-schema-export --list-exporter 
i has a this error:
MySQL Workbench Schema Exporter version 2.1.6-dev.
Copyright (c) 2010-2014 Johannes Mueller <circus2@web.de>
Copyright (c) 2012-2014 Toha <tohenk@yahoo.com>

Supported exporter:
PHP Warning:  max(): Array must contain at least one element in /home/willy/tip/mysql-workbench-schema-exporter/bin/mysql-workbench-schema-export on line 204

**Comment by jocelynduc** [comment]
I faced the same issue on my Symfony project with the Doctrine2 exporter. Just configured the versions like this to solve the problem:
```
"mysql-workbench-schema-exporter/mysql-workbench-schema-exporter": "dev-master as 3.0.0",
"mysql-workbench-schema-exporter/doctrine2-exporter": "3.0.0"
```

**Comment by rvock** [comment]
The various exporters are extra projects now. You should install the exporter you need for your project directly:
```
composer require --dev mysql-workbench-schema-exporter/doctrine2-exporter
```

If you only install the schema-exporter without a plugin and run `--list-exporter` you will get a warning, if no exporters are installed (starting with version 3.0.1)
