### ISSUE TITLE
The --list-exporter operation would fail

### ISSUE THREAD

**Issue by skvskv** [mysql-workbench-schema-exporter/mysql-workbench-schema-exporter#157]
alex@ubuntu:~/.composer/vendor/bin$ ./mysql-workbench-schema-export
MySQL Workbench Schema Exporter version 2.1.6-dev.
Copyright (c) 2010-2014 Johannes Mueller circus2@web.de
Copyright (c) 2012-2014 Toha tohenk@yahoo.com

Usage:
mysql-workbench-schema-export [options] FILENAME [DEST]

Options:
--export=type       Select the exporter, for a list of available exporter
                    use --list-exporter option.
--config=file       Read file for export parameters, in JSON format.
--saveconfig        Save export parameters to file.
--list-exporter     List all available exporter.
--no-auto-config    Disable automatic config file lookup in the current
                    directory if no --config option specified. Normally,
                    application will looking config file named export.json.
--zip               Export as zip archive.
Press any key to continue...

alex@ubuntu:~/.composer/vendor/bin$ ./mysql-workbench-schema-export --list-exporter
MySQL Workbench Schema Exporter version 2.1.6-dev.
Copyright (c) 2010-2014 Johannes Mueller circus2@web.de
Copyright (c) 2012-2014 Toha tohenk@yahoo.com

Supported exporter:
PHP Warning:  max(): Array must contain at least one element in /home/alex/.composer/vendor/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter/bin/mysql-workbench-schema-export on line 204
PHP Stack trace:
PHP   1. {main}() /home/alex/.composer/vendor/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter/bin/mysql-workbench-schema-export:0
PHP   2. main() /home/alex/.composer/vendor/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter/bin/mysql-workbench-schema-export:363
PHP   3. listFormatter() /home/alex/.composer/vendor/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter/bin/mysql-workbench-schema-export:238
PHP   4. max() /home/alex/.composer/vendor/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter/bin/mysql-workbench-schema-export:204

**Comment by ivanwitzke** [comment]
Same problem for me..

**Comment by ivanwitzke** [comment]
Found the solution... the exporters have been moved to a separate repository.
[https://github.com/mysql-workbench-schema-exporter/doctrine2-exporter](https://github.com/mysql-workbench-schema-exporter/doctrine2-exporter)

**Comment by skvskv** [comment]
Yeah, and they work pretty well, which is great! ) Yet somehow they ain't getting listed even when installed (composer require ...), so one got to guess exact name (doctrine2-annotation, doctrine2-yaml, etc) to have them do their job.

**Comment by rvock** [comment]
I've added a warning to the list-exporter command, when no exporters are found:
```
ERROR: No formatters found. Formatters are separate projects which need to be installed via composer.
       You can find all formatters at https://github.com/mysql-workbench-schema-exporter.
  Example:
  php composer.phar require --dev mysql-workbench-schema-exporter/doctrine2-exporter
```

@skvskv Could you try the new version? If a formatter is installed in vendor/mysql-workbench-schema-exporter/doctrine2-exporter, it should be listed:
```
rvock ~/projekte/mwb-test $ vendor/bin/mysql-workbench-schema-export --list-exporter
MySQL Workbench Schema Exporter version 3.0.2.
Copyright (c) 2010-2016 Johannes Mueller <circus2@web.de>
Copyright (c) 2012-2016 Toha <tohenk@yahoo.com>

Supported exporter:
1. doctrine2-annotation                Doctrine 2.0 Annotation Classes
2. doctrine2-yaml                      Doctrine 2.0 YAML
3. doctrine2-zf2inputfilterannotation  Doctrine 2.0 Annotation with ZF2 input filter Classes
```

If it's not, could you tell us, where everything is installed? Is everything within vendor/mysql-workbench-schema-export ? And which OS are you using?

**Comment by skvskv** [comment]
Works fine with 3.0.2, thanks for support!
