### ISSUE TITLE
ForeignKey Comment not being read

### ISSUE THREAD

**Issue by cesaric** [mysql-workbench-schema-exporter/mysql-workbench-schema-exporter#163]
The **db.mysql.ForeignKey** comment parameter isn't being used by Workbench.  So Model Comment Behaviors such as _{d:owningSide}true{/d:owningSide}_ (applied to ForeignKey) aren't working.

It appears Workbench is now placing ForeignKey comments in **model.Connection >>  workbench.physical.Connection** .  Within that Connection object, there's a link back to the ForeignKey object.  

Maybe we change the **parseComment()** function in **MwbExporter\Model\Base.php** so that "$this" is checked first for a Table or ForeignKey?  Then we can return the comment accordingly.  I'm assuming workbench.physical.Connection(s) are already in memory by the time we get to parseComment().

**Comment by andrekings** [comment]
I'm not related with this project. Sorry!

**Comment by tohenk** [comment]
Works as expected.
