### ISSUE TITLE
The URL for updating MySQL reserved words is incorrect

### ISSUE THREAD

**Issue by wildcodeman** [mysql-workbench-schema-exporter/mysql-workbench-schema-exporter#167]
When I run then script ./bin/update-mysql-reserved-words, it raised an error:

> PHP Warning:  file_get_contents(http://dev.mysql.com/doc/mysqld-version-reference/en/mysqld-version-reference-reservedwords-5-7.html): failed to open stream: HTTP request failed! HTTP/1.0 404 Not Found

I have checked the URL from http://dev.mysql.com, the correct url is https://dev.mysql.com/doc/mysqld-version-reference/en/mysqld-version-reference-keywords-5-7.html.

**Comment by johmue** [comment]
Thx
