### ISSUE TITLE
Cannot export a mwb file with space in file or dirname

### ISSUE THREAD

**Issue by nbrignol** [mysql-workbench-schema-exporter/mysql-workbench-schema-exporter#168]
Caused by simplexml_load_file in MwbExporter\Model\Document.readXML

We can use file_get_contents + simplexml_load_string instead.
I'll try to make a pull request if I find time.

```
$name = "zip://".str_replace("\\", "/", realpath($filename))."#document.mwb.xml";
$this->xml = simplexml_load_string(file_get_contents($name));
```

**Comment by tohenk** [comment]
Seem works as expected on latest release.
