### ISSUE TITLE
@ORM\HasLifecycleCallbacks

### ISSUE THREAD

**Issue by malutanpetronel** [mysql-workbench-schema-exporter/mysql-workbench-schema-exporter#170]
In my case I was unable to add @ORM and it seems it is needed for lifecycle
(see https://symfony.com/doc/current/doctrine/lifecycle_callbacks.html)

-            ->writeIf($lifecycleCallbacks, ' * @HasLifecycleCallbacks')
+            ->writeIf($lifecycleCallbacks, ' * @ORM\HasLifecycleCallbacks')

![image](https://user-images.githubusercontent.com/5830216/52798954-9fb71100-3081-11e9-986e-c0e27f4dbd4f.png)

**Comment by malutanpetronel** [comment]
yes and bellow
->write(' * @%s', ucfirst($callback))
+                                ->write(' * @ORM\%s', ucfirst($callback))

**Comment by Benew** [comment]
Anything on this ?

**Comment by tohenk** [comment]
Will be fixed in doctrine2-exporter.
