### ISSUE TITLE
Compatibility with PHP 5.x and doctrine/inflector

### ISSUE THREAD

**Issue by adrianbardan** [mysql-workbench-schema-exporter/mysql-workbench-schema-exporter#178]
After the updates with version 3.1 the library doesn't really work anymore with PHP 5.x because it uses the latest version of the API from the doctrine/inflector library (1.4 and above), which requires PHP ^7.2.

On PHP 5.6 composer installs doctrine/inflector 1.1 (latest one working on PHP 5.x), which has a totally different API and breaks the library.

I think the composer requirements should be changed as follows:

"require" : {
		"php" : ">=7.2.0",
		"doctrine/inflector": "^1.4 || ^2.0"
	}

I guess other dependent libraries will be affected too.

**Comment by tohenk** [comment]
I'm aware of this situation.
Well, it is necessary to retain this release (3.x branch) to be PHP 5.4 compatible, so we need to use older Doctrine Inflector API.
I suggest to create new 4.x branch which supports new features of PHP 7 along with new Doctrine Inflector API 2.0.
CC @johmue, @rvock.

**Comment by johmue** [comment]
@tohenk I am bit lost in this discussions. So I am with you here - whatever you suggest is fine for me. Thank you for taking care.
